import type { IDay, IMonth } from '@/types';
import { describe, it, expect } from 'vitest';
import { generateDays } from '@/helpers';

describe('generateDays', () => {
  const months: Array<IMonth> = [
    {
      id: '042024',
      name: 'April',
      monthString: new Date('2024-04-01'),
      isCurrent: true,
    },
  ];

  it('should generate days for given months', () => {
    const days: Array<IDay> = generateDays(months);

    expect(days).toEqual([
      {
        id: '30042024',
        monthId: '042024',
        number: '30',
        name: 'Tuesday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '29042024',
        monthId: '042024',
        number: '29',
        name: 'Monday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '28042024',
        monthId: '042024',
        number: '28',
        name: 'Sunday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '27042024',
        monthId: '042024',
        number: '27',
        name: 'Saturday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '26042024',
        monthId: '042024',
        number: '26',
        name: 'Friday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '25042024',
        monthId: '042024',
        number: '25',
        name: 'Thursday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '24042024',
        monthId: '042024',
        number: '24',
        name: 'Wednesday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '23042024',
        monthId: '042024',
        number: '23',
        name: 'Tuesday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '22042024',
        monthId: '042024',
        number: '22',
        name: 'Monday',
        isCurrent: false,
        isPast: false,
      },
      {
        id: '21042024',
        monthId: '042024',
        number: '21',
        name: 'Sunday',
        isCurrent: true,
        isPast: false,
      },
      {
        id: '20042024',
        monthId: '042024',
        number: '20',
        name: 'Saturday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '19042024',
        monthId: '042024',
        number: '19',
        name: 'Friday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '18042024',
        monthId: '042024',
        number: '18',
        name: 'Thursday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '17042024',
        monthId: '042024',
        number: '17',
        name: 'Wednesday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '16042024',
        monthId: '042024',
        number: '16',
        name: 'Tuesday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '15042024',
        monthId: '042024',
        number: '15',
        name: 'Monday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '14042024',
        monthId: '042024',
        number: '14',
        name: 'Sunday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '13042024',
        monthId: '042024',
        number: '13',
        name: 'Saturday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '12042024',
        monthId: '042024',
        number: '12',
        name: 'Friday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '11042024',
        monthId: '042024',
        number: '11',
        name: 'Thursday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '10042024',
        monthId: '042024',
        number: '10',
        name: 'Wednesday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '09042024',
        monthId: '042024',
        number: '9',
        name: 'Tuesday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '08042024',
        monthId: '042024',
        number: '8',
        name: 'Monday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '07042024',
        monthId: '042024',
        number: '7',
        name: 'Sunday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '06042024',
        monthId: '042024',
        number: '6',
        name: 'Saturday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '05042024',
        monthId: '042024',
        number: '5',
        name: 'Friday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '04042024',
        monthId: '042024',
        number: '4',
        name: 'Thursday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '03042024',
        monthId: '042024',
        number: '3',
        name: 'Wednesday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '02042024',
        monthId: '042024',
        number: '2',
        name: 'Tuesday',
        isCurrent: false,
        isPast: true,
      },
      {
        id: '01042024',
        monthId: '042024',
        number: '1',
        name: 'Monday',
        isCurrent: false,
        isPast: true,
      },
    ]);
  });
});
